server:
  port: 8080

logging:
  level:
    org.springframework.boot.context.config: DEBUG

spring:
  config:
    activate:
      on-profile: default
    import: "file:./.env[.properties]"
  application:
    name: vulpes

vulpes:
  github:
    advisory-database:
      path: "${HOME}/Projects/github.com/github/advisory-database"
  opensearch:
    url: https://localhost:9200
