logging:
  level:
    org.springframework.boot.context.config: INFO

spring:
  config:
    activate:
      on-profile: prod
    import:
      - "file:/opt/secrets/.env[.properties]"
      - "file:/opt/secrets/.db.env[.properties]"
  application:
    name: vulpes
  datasource:
    url: jdbc:postgresql://postgresql:5432/vulpes_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  # Enable graceful shutdown
  lifecycle:
    timeout-per-shutdown-phase: "10s"

vulpes:
  github:
    advisory-database:
      fetch-interval: 20m
      path: /opt/data/github/advisory-database
  opensearch:
    url: https://opensearch-node:9200
    index: "github-security-advisory-database"
  web-ui:
    url: http://localhost:3000
  load-data-from-scratch:
    opensearch: false
    postgresql: false
