server:
  port: 8080

logging:
  level:
    org.springframework.boot.context.config: DEBUG

spring:
  config:
    activate:
      on-profile: default
  application:
    name: vulpes
  datasource:
    url: jdbc:postgresql://localhost:5432/vulpes
    username: vulpes_db_user
    password: vulpes_db_password
  jpa:
    open-in-view: off
    show-sql: true

vulpes:
  github:
    advisory-database:
      path: ./data/github/advisory-database
