CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    previous_commit_id VARCHAR(255) NOT NULL,
    current_commit_id VARCHAR(255),
    created_at TIMESTAMP,
    changed_states JSON
);

CREATE SEQUENCE IF NOT EXISTS audit_log_seq INCREMENT BY 50;

GRANT ALL PRIVILEGES ON TABLE audit_log TO vulpes_user;

GRANT ALL PRIVILEGES ON SEQUENCE audit_log_seq TO vulpes_user;
