CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    previous_commit_id VARCHAR(255) NOT NULL,
    current_commit_id VARCHAR(255),
    created_at TIMESTAMP,
    changed_states JSON
);

CREATE SEQUENCE IF NOT EXISTS audit_log_seq INCREMENT BY 50;
